export const BIZFILE_ENTITY_TYPE_OPTIONS = [
  'PRIVATE_LIMITED', 'EXEMPTED_PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'PUBLIC_COMPANY_LIMITED_BY_GUARANTEE',
  'SOLE_PROPRIETORSHIP', 'PARTNERSHIP', 'LIMITED_PARTNERSHIP', 'LIMITED_LIABILITY_PARTNERSHIP',
  'FOREIGN_COMPANY', 'VARIABLE_CAPITAL_COMPANY', 'OTHER',
] as const;
export const BIZFILE_STATUS_OPTIONS = ['LIVE', 'STRUCK_OFF', 'WINDING_UP', 'DISSOLVED', 'IN_LIQUIDATION', 'IN_RECEIVERSHIP', 'AMALGAMATED', 'CONVERTED', 'OTHER'] as const;
export const BIZFILE_OFFICER_ROLE_OPTIONS = ['DIRECTOR', 'MANAGING_DIRECTOR', 'ALTERNATE_DIRECTOR', 'NOMINEE_DIRECTOR', 'SECRETARY', 'CEO', 'CFO', 'AUDITOR', 'LIQUIDATOR', 'RECEIVER', 'JUDICIAL_MANAGER'] as const;
export const BIZFILE_IDENTIFICATION_TYPE_OPTIONS = ['NRIC', 'FIN', 'PASSPORT', 'UEN', 'OTHER'] as const;

type EntityType = typeof BIZFILE_ENTITY_TYPE_OPTIONS[number];
type CompanyStatus = typeof BIZFILE_STATUS_OPTIONS[number];
type OfficerRole = typeof BIZFILE_OFFICER_ROLE_OPTIONS[number];
type IdentificationType = typeof BIZFILE_IDENTIFICATION_TYPE_OPTIONS[number];

export const ENTITY_TYPE_ALIASES: Record<string, EntityType> = {
  PRIVATE_LIMITED: 'PRIVATE_LIMITED', 'PRIVATE LIMITED': 'PRIVATE_LIMITED', 'PRIVATE COMPANY LIMITED BY SHARES': 'PRIVATE_LIMITED',
  EXEMPTED_PRIVATE_LIMITED: 'EXEMPTED_PRIVATE_LIMITED', 'EXEMPTED PRIVATE LIMITED': 'EXEMPTED_PRIVATE_LIMITED', 'EXEMPT PRIVATE LIMITED': 'EXEMPTED_PRIVATE_LIMITED', 'EXEMPT PRIVATE COMPANY LIMITED BY SHARES': 'EXEMPTED_PRIVATE_LIMITED', 'EXEMPTED PRIVATE COMPANY LIMITED BY SHARES': 'EXEMPTED_PRIVATE_LIMITED',
  PUBLIC_LIMITED: 'PUBLIC_LIMITED', 'PUBLIC LIMITED': 'PUBLIC_LIMITED', 'PUBLIC COMPANY LIMITED BY SHARES': 'PUBLIC_LIMITED',
  PUBLIC_COMPANY_LIMITED_BY_GUARANTEE: 'PUBLIC_COMPANY_LIMITED_BY_GUARANTEE', 'PUBLIC COMPANY LIMITED BY GUARANTEE': 'PUBLIC_COMPANY_LIMITED_BY_GUARANTEE', 'PUBLIC LIMITED BY GUARANTEE': 'PUBLIC_COMPANY_LIMITED_BY_GUARANTEE',
  SOLE_PROPRIETORSHIP: 'SOLE_PROPRIETORSHIP', 'SOLE PROPRIETORSHIP': 'SOLE_PROPRIETORSHIP', PARTNERSHIP: 'PARTNERSHIP', LIMITED_PARTNERSHIP: 'LIMITED_PARTNERSHIP', 'LIMITED PARTNERSHIP': 'LIMITED_PARTNERSHIP',
  LIMITED_LIABILITY_PARTNERSHIP: 'LIMITED_LIABILITY_PARTNERSHIP', LLP: 'LIMITED_LIABILITY_PARTNERSHIP', FOREIGN_COMPANY: 'FOREIGN_COMPANY', 'FOREIGN COMPANY': 'FOREIGN_COMPANY', VARIABLE_CAPITAL_COMPANY: 'VARIABLE_CAPITAL_COMPANY', VCC: 'VARIABLE_CAPITAL_COMPANY', OTHER: 'OTHER',
};
export const COMPANY_STATUS_ALIASES: Record<string, CompanyStatus> = { LIVE: 'LIVE', 'LIVE COMPANY': 'LIVE', STRUCK_OFF: 'STRUCK_OFF', 'STRUCK OFF': 'STRUCK_OFF', WINDING_UP: 'WINDING_UP', 'WINDING UP': 'WINDING_UP', DISSOLVED: 'DISSOLVED', IN_LIQUIDATION: 'IN_LIQUIDATION', 'IN LIQUIDATION': 'IN_LIQUIDATION', IN_RECEIVERSHIP: 'IN_RECEIVERSHIP', 'IN RECEIVERSHIP': 'IN_RECEIVERSHIP', AMALGAMATED: 'AMALGAMATED', CONVERTED: 'CONVERTED', OTHER: 'OTHER' };
export const OFFICER_ROLE_ALIASES: Record<string, OfficerRole> = { DIRECTOR: 'DIRECTOR', MANAGING_DIRECTOR: 'MANAGING_DIRECTOR', 'MANAGING DIRECTOR': 'MANAGING_DIRECTOR', ALTERNATE_DIRECTOR: 'ALTERNATE_DIRECTOR', 'ALTERNATE DIRECTOR': 'ALTERNATE_DIRECTOR', NOMINEE_DIRECTOR: 'NOMINEE_DIRECTOR', 'NOMINEE DIRECTOR': 'NOMINEE_DIRECTOR', SECRETARY: 'SECRETARY', 'COMPANY SECRETARY': 'SECRETARY', CEO: 'CEO', 'CHIEF EXECUTIVE OFFICER': 'CEO', CFO: 'CFO', 'CHIEF FINANCIAL OFFICER': 'CFO', AUDITOR: 'AUDITOR', LIQUIDATOR: 'LIQUIDATOR', RECEIVER: 'RECEIVER', JUDICIAL_MANAGER: 'JUDICIAL_MANAGER', 'JUDICIAL MANAGER': 'JUDICIAL_MANAGER' };
export const IDENTIFICATION_TYPE_ALIASES: Record<string, IdentificationType> = { NRIC: 'NRIC', 'NATIONAL REGISTRATION IDENTITY CARD': 'NRIC', FIN: 'FIN', 'FOREIGN IDENTIFICATION NUMBER': 'FIN', PASSPORT: 'PASSPORT', UEN: 'UEN', 'UNIQUE ENTITY NUMBER': 'UEN', OTHER: 'OTHER' };

function canonicalize(value: unknown, aliases: Record<string, string>): unknown {
  if (typeof value !== 'string') return value;
  const trimmed = value.trim();
  return aliases[trimmed.toUpperCase()] ?? trimmed;
}
export const canonicalizeEntityType = (value: unknown) => canonicalize(value, ENTITY_TYPE_ALIASES);
export const canonicalizeCompanyStatus = (value: unknown) => canonicalize(value, COMPANY_STATUS_ALIASES);
export const canonicalizeOfficerRole = (value: unknown) => canonicalize(value, OFFICER_ROLE_ALIASES);
export const canonicalizeIdentificationType = (value: unknown) => canonicalize(value, IDENTIFICATION_TYPE_ALIASES);
