'use client';

import { useMemo, useState } from 'react';
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { CheckSquare, FileText, GripVertical, Mail, PenLine, Plus, Trash2, Building2, CircleCheckBig } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { FormInput } from '@/components/ui/form-input';
import { Toggle } from '@/components/ui/toggle';
import type { TaskPipeline } from '@/hooks/use-task-pipelines';
import type { TaskPipelineCreatePayload } from '@/services/tasks/types';

type ActionType = 'MANUAL' | 'COMPANY_PROFILE' | 'DOCUMENT_GENERATION' | 'ESIGNING';
type ChecklistItem = { label: string; position?: number };
type StageDraft = { id: string; name: string; description: string; actionType: ActionType; icon: string; isRequired: boolean; actionConfig: Record<string, unknown>; checklistItems: ChecklistItem[] };
export type PipelineDraft = { name: string; description: string; stages: StageDraft[] };
export type TemplateOption = { id: string; name: string };

const ACTION_DEFAULTS: Record<ActionType, string> = { MANUAL: 'CircleCheckBig', COMPANY_PROFILE: 'Building2', DOCUMENT_GENERATION: 'FileText', ESIGNING: 'PenLine' };
const ICONS = [{ name: 'CircleCheckBig', Icon: CircleCheckBig }, { name: 'Building2', Icon: Building2 }, { name: 'FileText', Icon: FileText }, { name: 'PenLine', Icon: PenLine }, { name: 'Mail', Icon: Mail }, { name: 'CheckSquare', Icon: CheckSquare }];

function id() { return `stage-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function blankStage(index: number): StageDraft { return { id: id(), name: `Stage ${index + 1}`, description: '', actionType: 'MANUAL', icon: 'CircleCheckBig', isRequired: true, actionConfig: {}, checklistItems: [] }; }
function checklistFromConfig(config: Record<string, unknown> | null) { return Array.isArray(config?.checklistItems) ? config.checklistItems.filter((item): item is ChecklistItem => Boolean(item && typeof item === 'object' && typeof (item as ChecklistItem).label === 'string')) : []; }

export function pipelineToDraft(pipeline: TaskPipeline): PipelineDraft {
  const version = pipeline.versions[0];
  return { name: pipeline.name, description: pipeline.description ?? '', stages: (version?.stages ?? []).slice().sort((a, b) => a.position - b.position).map((stage) => ({ id: stage.id, name: stage.name, description: stage.description ?? '', actionType: stage.actionType, icon: stage.icon, isRequired: stage.isRequired, actionConfig: { ...(stage.actionConfig ?? {}) }, checklistItems: checklistFromConfig(stage.actionConfig) })) };
}

function SortableStage({ stage, index, templates, onChange, onRemove, onMove }: { stage: StageDraft; index: number; templates: TemplateOption[]; onChange: (next: StageDraft) => void; onRemove: () => void; onMove: (direction: -1 | 1) => void }) {
  const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: stage.id });
  const [iconSearch, setIconSearch] = useState('');
  const iconOptions = useMemo(() => ICONS.filter(({ name }) => name.toLowerCase().includes(iconSearch.toLowerCase())), [iconSearch]);
  const updateConfig = (patch: Record<string, unknown>) => onChange({ ...stage, actionConfig: { ...stage.actionConfig, ...patch } });
  return <article ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }} className="rounded-lg border border-border-primary bg-background-elevated p-3">
    <div className="mb-3 flex items-center gap-2"><button type="button" aria-label="Drag stage" className="cursor-grab rounded p-1 text-text-muted focus-visible:ring-2 focus-visible:ring-oak-primary" {...attributes} {...listeners}><GripVertical className="h-4 w-4" /></button><span data-testid="pipeline-stage-name" className="flex-1 text-sm font-semibold text-text-primary">{stage.name}</span><Button variant="ghost" size="xs" iconOnly aria-label="Move stage up" disabled={index === 0} onClick={() => onMove(-1)}>↑</Button><Button variant="ghost" size="xs" iconOnly aria-label="Move stage down" onClick={() => onMove(1)}>↓</Button><Button variant="ghost" size="xs" iconOnly aria-label="Remove stage" className="text-status-error" onClick={onRemove}><Trash2 /></Button></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><FormInput label="Stage name" value={stage.name} onChange={(event) => onChange({ ...stage, name: event.target.value })} /><FormInput label="Description" value={stage.description} onChange={(event) => onChange({ ...stage, description: event.target.value })} /></div>
    <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-medium text-text-secondary">Action type<select aria-label="Action type" value={stage.actionType} onChange={(event) => { const actionType = event.target.value as ActionType; onChange({ ...stage, actionType, icon: ACTION_DEFAULTS[actionType] }); }} className="mt-2 h-8 w-full rounded-lg border border-border-primary bg-background-primary px-3 text-sm text-text-primary"><option value="MANUAL">Manual</option><option value="COMPANY_PROFILE">Company profile</option><option value="DOCUMENT_GENERATION">Document generation</option><option value="ESIGNING">E-signing</option></select></label><Toggle size="sm" label={stage.isRequired ? 'Required stage' : 'Optional stage'} checked={stage.isRequired} onChange={(isRequired) => onChange({ ...stage, isRequired })} /></div>
    <div className="mt-3"><FormInput label="Search icons" value={iconSearch} onChange={(event) => setIconSearch(event.target.value)} placeholder="Search curated icons" /><div className="mt-2 flex flex-wrap gap-2">{iconOptions.map(({ name, Icon }) => <button key={name} type="button" aria-label={name} onClick={() => onChange({ ...stage, icon: name })} className={`inline-flex h-8 w-8 items-center justify-center rounded border ${stage.icon === name ? 'border-oak-primary bg-oak-primary/10' : 'border-border-primary'} text-text-secondary focus-visible:ring-2 focus-visible:ring-oak-primary`}><Icon className="h-4 w-4" /></button>)}</div></div>
    {stage.actionType === 'DOCUMENT_GENERATION' && <label className="mt-3 block text-xs font-medium text-text-secondary">Default document template <span className="font-normal text-text-muted">(optional)</span><select aria-label="Default document template" value={typeof stage.actionConfig.templateId === 'string' ? stage.actionConfig.templateId : ''} onChange={(event) => updateConfig({ templateId: event.target.value || undefined })} className="mt-2 h-8 w-full rounded-lg border border-border-primary bg-background-primary px-3 text-sm text-text-primary"><option value="">Let task users choose</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label>}
    <div className="mt-3 border-t border-border-primary pt-3"><div className="flex items-center justify-between"><span className="text-xs font-medium text-text-secondary">Checklist</span><Button variant="ghost" size="xs" leftIcon={<Plus />} onClick={() => onChange({ ...stage, checklistItems: [...stage.checklistItems, { label: '' }] })} aria-label="Add checklist item">Add item</Button></div><div className="mt-2 space-y-2">{stage.checklistItems.map((item, itemIndex) => <div key={`${stage.id}-${itemIndex}`} className="flex gap-2"><input aria-label={`Checklist item ${itemIndex + 1}`} value={item.label} onChange={(event) => onChange({ ...stage, checklistItems: stage.checklistItems.map((entry, entryIndex) => entryIndex === itemIndex ? { ...entry, label: event.target.value } : entry) })} className="h-8 min-w-0 flex-1 rounded-lg border border-border-primary bg-background-primary px-3 text-sm text-text-primary" /><Button variant="ghost" size="xs" iconOnly aria-label="Remove checklist item" onClick={() => onChange({ ...stage, checklistItems: stage.checklistItems.filter((_, entryIndex) => entryIndex !== itemIndex) })}><Trash2 /></Button></div>)}</div></div>
  </article>;
}

export function PipelineBuilder({ initialDraft, templates, onCancel, onSave, isSaving = false }: { initialDraft: PipelineDraft; templates: TemplateOption[]; onCancel: () => void; onSave: (draft: TaskPipelineCreatePayload) => void; isSaving?: boolean }) {
  const [draft, setDraft] = useState(initialDraft); const [errors, setErrors] = useState<string[]>([]);
  const sensors = useSensors(useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  const move = (from: number, to: number) => setDraft((value) => ({ ...value, stages: to < 0 || to >= value.stages.length ? value.stages : arrayMove(value.stages, from, to) }));
  const save = () => { const nextErrors = [!draft.name.trim() && 'Pipeline name is required', draft.stages.length === 0 && 'Add at least one stage', ...draft.stages.map((stage, index) => !stage.name.trim() && `Stage ${index + 1} name is required`)].filter(Boolean) as string[]; setErrors(nextErrors); if (nextErrors.length) return; onSave({ name: draft.name.trim(), description: draft.description.trim() || null, stages: draft.stages.map((stage, position) => ({ name: stage.name.trim(), description: stage.description.trim() || null, position, actionType: stage.actionType, icon: stage.icon, isRequired: stage.isRequired, actionConfig: { ...stage.actionConfig }, checklistItems: stage.checklistItems.filter((item) => item.label.trim()).map((item, itemPosition) => ({ label: item.label.trim(), position: itemPosition })) })) }); };
  return <form onSubmit={(event) => { event.preventDefault(); save(); }} className="mx-auto max-w-4xl space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-semibold text-text-primary">{initialDraft.name ? 'Edit pipeline' : 'New pipeline'}</h1><p className="mt-1 text-sm text-text-secondary">Saving publishes a new version for future tasks.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" isLoading={isSaving} aria-label="Save pipeline">Save pipeline</Button></div></div>{errors.length > 0 && <div role="alert" className="rounded-lg border border-status-error/30 bg-status-error/10 p-3 text-sm text-status-error">{errors.map((error) => <p key={error}>{error}</p>)}</div>}<div className="card space-y-3 p-4"><FormInput label="Pipeline name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><label className="block text-xs font-medium text-text-secondary">Description<textarea aria-label="Pipeline description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} rows={3} className="mt-2 w-full rounded-lg border border-border-primary bg-background-primary px-3 py-2 text-sm text-text-primary" /></label></div><section aria-label="Pipeline stages" className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-text-primary">Stages</h2><Button variant="secondary" size="sm" leftIcon={<Plus />} onClick={() => setDraft({ ...draft, stages: [...draft.stages, blankStage(draft.stages.length)] })} aria-label="Add stage">Add stage</Button></div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={(event: DragEndEvent) => { const oldIndex = draft.stages.findIndex((stage) => stage.id === event.active.id); const newIndex = draft.stages.findIndex((stage) => stage.id === event.over?.id); if (oldIndex >= 0 && newIndex >= 0) move(oldIndex, newIndex); }}><SortableContext items={draft.stages.map((stage) => stage.id)} strategy={verticalListSortingStrategy}>{draft.stages.map((stage, index) => <SortableStage key={stage.id} stage={stage} index={index} templates={templates} onChange={(next) => setDraft({ ...draft, stages: draft.stages.map((entry) => entry.id === next.id ? next : entry) })} onRemove={() => setDraft({ ...draft, stages: draft.stages.filter((entry) => entry.id !== stage.id) })} onMove={(direction) => move(index, index + direction)} />)}</SortableContext></DndContext></section></form>;
}
