'use client';

import { useMemo, useState } from 'react';
import { Check, ChevronDown, ChevronRight, Copy, Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Modal, ModalBody, ModalFooter } from '@/components/ui/modal';
import {
  TEMPLATE_COLLECTION_OPTIONS,
  TEMPLATE_FIELD_OPTIONS,
  buildConditionBlock,
  buildEachBlock,
  type ConditionOperator,
  type TemplateCollection,
  type TemplateLoopLayout,
} from '@/components/documents/template-editor/template-builders';
import type { CustomPlaceholderDefinition, MergedPlaceholder } from '@/types/placeholders';

export interface TemplatePartialOption {
  id: string;
  name: string;
  displayName?: string | null;
  description?: string | null;
}

export interface PlaceholderPanelProps {
  onInsert: (html: string) => void;
  partials: TemplatePartialOption[];
  isLoadingPartials: boolean;
  customPlaceholders: CustomPlaceholderDefinition[];
  onCustomPlaceholdersChange: (placeholders: CustomPlaceholderDefinition[]) => void;
  mergedPlaceholders?: MergedPlaceholder[];
  templateBooleanPlaceholders?: CustomPlaceholderDefinition[];
  partialPlaceholderLinkings?: Record<string, string>;
  onPartialPlaceholderLinkingChange?: (key: string, linkedTo: string | undefined) => void;
  isPartialMode?: boolean;
}

interface Field {
  key: string;
  label: string;
  example: string;
  category: string;
  guided?: 'loop-directors' | 'loop-shareholders' | 'condition';
}

interface FieldCategory {
  key: string;
  label: string;
  fields: Field[];
}

const FIELD_CATEGORIES: FieldCategory[] = [
  {
    key: 'company', label: 'Company', fields: [
      { key: 'company.name', label: 'Company Name', example: 'Sample Company Pte Ltd', category: 'Company' },
      { key: 'company.uen', label: 'UEN', example: '202312345A', category: 'Company' },
      { key: 'company.registeredAddress', label: 'Full Address', example: '123 Sample Street, Singapore 123456', category: 'Company' },
      { key: 'company.address.block', label: 'Block', example: '123', category: 'Company' },
      { key: 'company.address.street', label: 'Street Name', example: 'Sample Street', category: 'Company' },
      { key: 'company.address.level', label: 'Level', example: '01', category: 'Company' },
      { key: 'company.address.unit', label: 'Unit', example: '01', category: 'Company' },
      { key: 'company.address.building', label: 'Building Name', example: 'Sample Building', category: 'Company' },
      { key: 'company.address.postalCode', label: 'Postal Code', example: '123456', category: 'Company' },
      { key: 'company.incorporationDate', label: 'Incorporation Date', example: '15 January 2023', category: 'Company' },
      { key: 'company.entityType', label: 'Entity Type', example: 'Private Limited Company', category: 'Company' },
      { key: 'company.capital', label: 'Share Capital', example: '$100,000', category: 'Company' },
    ],
  },
  {
    key: 'directors', label: 'Directors', fields: [
      { key: 'loop-directors', label: 'Directors loop', example: 'Repeat content for every director', category: 'Loops', guided: 'loop-directors' },
      { key: 'this.name', label: 'Director Name', example: 'John Tan Wei Ming', category: 'Directors' },
      { key: 'this.identificationNumber', label: 'Director ID', example: 'S1234567A', category: 'Directors' },
      { key: 'this.nationality', label: 'Director Nationality', example: 'Singaporean', category: 'Directors' },
      { key: 'this.address', label: 'Director Address', example: '123 Sample Street', category: 'Directors' },
      { key: 'directors[0].name', label: 'First Director Name', example: 'John Tan Wei Ming', category: 'Directors' },
    ],
  },
  {
    key: 'shareholders', label: 'Shareholders', fields: [
      { key: 'loop-shareholders', label: 'Shareholders loop', example: 'Repeat content for every shareholder', category: 'Loops', guided: 'loop-shareholders' },
      { key: 'this.name', label: 'Shareholder Name', example: 'Mary Lee Mei Ling', category: 'Shareholders' },
      { key: 'this.shareClass', label: 'Share Class', example: 'Ordinary', category: 'Shareholders' },
      { key: 'this.numberOfShares', label: 'Number of Shares', example: '50,000', category: 'Shareholders' },
      { key: 'this.percentageHeld', label: 'Percentage Held', example: '50%', category: 'Shareholders' },
      { key: 'shareholders[0].name', label: 'First Shareholder Name', example: 'Mary Lee Mei Ling', category: 'Shareholders' },
    ],
  },
  {
    key: 'conditions', label: 'Conditions', fields: [
      { key: 'condition', label: 'Conditional block', example: 'Show content when a field matches', category: 'Conditions', guided: 'condition' },
    ],
  },
  {
    key: 'system', label: 'System', fields: [
      { key: 'system.currentDate', label: 'Current Date', example: '6 December 2024', category: 'System' },
      { key: 'system.generatedBy', label: 'Generated By', example: 'John Doe', category: 'System' },
    ],
  },
  {
    key: 'modifiers', label: 'Modifiers', fields: [
      { key: 'UCASE({{field}})', label: 'Uppercase', example: 'SAMPLE COMPANY PTE LTD', category: 'Modifiers' },
      { key: 'LCASE({{field}})', label: 'Lowercase', example: 'sample company pte ltd', category: 'Modifiers' },
      { key: 'PCASE({{field}})', label: 'Proper Case', example: 'Sample Company Pte Ltd', category: 'Modifiers' },
    ],
  },
];

const CONDITION_FIELDS = [
  'company.name', 'company.uen', 'company.registeredAddress', 'company.incorporationDate',
  'company.entityType', 'company.capital', 'contact.name', 'contact.email',
  'system.currentDate', 'system.generatedBy', 'system.tenantName',
];

function toPlaceholder(key: string) {
  return key.startsWith('{{') || /^[ULP]CASE\(/.test(key) ? key : `{{${key}}}`;
}

function normalizeKey(value: string) {
  return value.toLowerCase().trim().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
}

function escapeText(value: string) {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function PlaceholderPanel({
  onInsert,
  partials,
  isLoadingPartials,
  customPlaceholders,
  onCustomPlaceholdersChange,
  mergedPlaceholders = [],
  templateBooleanPlaceholders = [],
  partialPlaceholderLinkings = {},
  onPartialPlaceholderLinkingChange,
  isPartialMode = false,
}: PlaceholderPanelProps) {
  const [query, setQuery] = useState('');
  const [expandedCategories, setExpandedCategories] = useState<string[]>(['company', 'directors', 'shareholders', 'conditions']);
  const [recentKeys, setRecentKeys] = useState<string[]>([]);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [activeBuilder, setActiveBuilder] = useState<'loop-directors' | 'loop-shareholders' | 'condition' | null>(null);
  const [isAddingCustom, setIsAddingCustom] = useState(false);
  const [customForm, setCustomForm] = useState({ label: '', key: '', type: 'text' as CustomPlaceholderDefinition['type'], required: true, defaultValue: '' });

  const filteredCategories = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    if (!normalizedQuery) return FIELD_CATEGORIES;
    return FIELD_CATEGORIES.map((category) => ({
      ...category,
      fields: category.fields.filter((field) =>
        [field.label, field.key, field.category, field.example, category.label]
          .join(' ').toLowerCase().includes(normalizedQuery)),
    })).filter((category) => category.fields.length > 0);
  }, [query]);

  const allFields = useMemo(() => FIELD_CATEGORIES.flatMap((category) => category.fields), []);
  const recentFields = recentKeys.map((key) => allFields.find((field) => field.key === key)).filter((field): field is Field => Boolean(field));
  const duplicateKey = Boolean(customForm.key) && customPlaceholders.some((field) => field.key === normalizeKey(customForm.key));

  const insert = (value: string, recentKey = value) => {
    onInsert(value);
    setRecentKeys((previous) => [recentKey, ...previous.filter((key) => key !== recentKey)].slice(0, 5));
  };

  const copy = async (value: string, key: string) => {
    await navigator.clipboard?.writeText(value);
    setCopiedKey(key);
    window.setTimeout(() => setCopiedKey(null), 2000);
  };

  const saveCustomField = () => {
    const key = normalizeKey(customForm.key);
    if (!customForm.label.trim() || !key || duplicateKey) return;
    onCustomPlaceholdersChange([...customPlaceholders, {
      id: crypto.randomUUID(),
      key,
      label: customForm.label.trim(),
      type: customForm.type,
      required: customForm.required,
      defaultValue: customForm.type === 'boolean' ? (customForm.defaultValue.trim() || 'false') : (customForm.defaultValue.trim() || undefined),
    }]);
    setCustomForm({ label: '', key: '', type: 'text', required: true, defaultValue: '' });
    setIsAddingCustom(false);
  };

  const renderField = (field: Field) => (
    <div key={field.key} className="group flex items-center gap-2 rounded-md px-2 py-2 hover:bg-background-tertiary">
      <div className="min-w-0 flex-1">
        <div className="text-xs font-medium text-text-primary">{field.label}</div>
        <div className="truncate font-mono text-[11px] text-accent-primary">{field.guided ? 'Guided builder' : toPlaceholder(field.key)}</div>
        <div className="truncate text-[11px] text-text-muted">Example: {field.example}</div>
      </div>
      <Button
        size="xs"
        variant="primary"
        aria-label={field.guided === 'loop-directors' ? 'Build directors loop' : field.guided === 'loop-shareholders' ? 'Build shareholders loop' : field.guided === 'condition' ? 'Build condition' : `Insert ${field.label}`}
        onClick={() => field.guided ? setActiveBuilder(field.guided) : insert(toPlaceholder(field.key), field.key)}
      >
        {field.guided ? 'Build' : 'Insert'}
      </Button>
      <Button
        size="xs"
        variant="ghost"
        iconOnly
        aria-label={`Copy ${field.label}`}
        onClick={() => copy(field.guided ? '' : toPlaceholder(field.key), field.key)}
        disabled={Boolean(field.guided)}
      >
        {copiedKey === field.key ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
      </Button>
    </div>
  );

  return (
    <div className="flex h-full flex-col bg-background-secondary">
      <div className="border-b border-border-primary p-3">
        <label htmlFor="placeholder-search" className="sr-only">Search fields</label>
        <input
          id="placeholder-search"
          type="search"
          role="searchbox"
          aria-label="Search fields"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Search fields"
          className="h-8 w-full rounded-md border border-border-primary bg-background-primary px-3 text-xs text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-accent-primary/50"
        />
      </div>

      <div className="flex-1 overflow-y-auto p-2">
        {recentFields.length > 0 && !query && (
          <section className="mb-2 rounded-md border border-border-primary">
            <h3 className="px-2 py-2 text-xs font-semibold text-text-primary">Recently used</h3>
            {recentFields.map(renderField)}
          </section>
        )}

        {filteredCategories.map((category) => {
          const isOpen = query.length > 0 || expandedCategories.includes(category.key);
          return (
            <section key={category.key} className="mb-2 rounded-md border border-border-primary">
              <button
                type="button"
                className="flex w-full items-center justify-between px-2 py-2 text-left hover:bg-background-tertiary"
                onClick={() => setExpandedCategories((previous) => previous.includes(category.key) ? previous.filter((key) => key !== category.key) : [...previous, category.key])}
                aria-expanded={isOpen}
              >
                <span className="text-xs font-semibold text-text-primary">{category.label}</span>
                <span className="flex items-center gap-2 text-[11px] text-text-muted"><span className="rounded-full bg-background-tertiary px-1.5 py-0.5">{category.fields.length}</span>{isOpen ? <ChevronDown className="h-3.5 w-3.5" /> : <ChevronRight className="h-3.5 w-3.5" />}</span>
              </button>
              {isOpen && <div className="border-t border-border-secondary">{category.fields.map(renderField)}</div>}
            </section>
          );
        })}

        {query && filteredCategories.length === 0 && (
          <div className="p-4 text-center text-xs text-text-muted">No fields match this search. Clear it or create a custom field.</div>
        )}

        <section className="mb-2 rounded-md border border-border-primary">
          <div className="flex items-center justify-between px-2 py-2">
            <div><h3 className="text-xs font-semibold text-text-primary">Custom</h3><p className="text-[11px] text-text-muted">Fields requested during generation.</p></div>
            {!isAddingCustom && <Button size="xs" variant="secondary" leftIcon={<Plus />} onClick={() => setIsAddingCustom(true)}>Add custom field</Button>}
          </div>
          {isAddingCustom && (
            <div className="space-y-3 border-t border-border-secondary p-3">
              <div><label htmlFor="custom-field-label" className="mb-1 block text-xs font-medium text-text-secondary">Field label</label><input id="custom-field-label" value={customForm.label} onChange={(event) => setCustomForm((previous) => ({ ...previous, label: event.target.value, key: previous.key || normalizeKey(event.target.value) }))} className="h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary" /></div>
              <div><label htmlFor="custom-field-key" className="mb-1 block text-xs font-medium text-text-secondary">Field key</label><input id="custom-field-key" value={customForm.key} onChange={(event) => setCustomForm((previous) => ({ ...previous, key: event.target.value }))} className="h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 font-mono text-xs text-text-primary" />{duplicateKey && <p className="mt-1 text-xs text-status-error">This placeholder key already exists.</p>}</div>
              <div className="grid grid-cols-2 gap-2"><label className="text-xs font-medium text-text-secondary">Type<select value={customForm.type} onChange={(event) => setCustomForm((previous) => ({ ...previous, type: event.target.value as CustomPlaceholderDefinition['type'] }))} className="mt-1 h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary"><option value="text">Text</option><option value="textarea">Long text</option><option value="date">Date</option><option value="number">Number</option><option value="currency">Currency</option><option value="boolean">Boolean</option></select></label><label className="text-xs font-medium text-text-secondary">Default value<input value={customForm.defaultValue} onChange={(event) => setCustomForm((previous) => ({ ...previous, defaultValue: event.target.value }))} className="mt-1 h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary" /></label></div>
              <label className="flex items-center gap-2 text-xs text-text-secondary"><input type="checkbox" checked={customForm.required} onChange={(event) => setCustomForm((previous) => ({ ...previous, required: event.target.checked }))} />Required</label>
              <p className="rounded bg-background-tertiary p-2 font-mono text-[11px] text-accent-primary">{`{{custom.${normalizeKey(customForm.key) || 'field_key'}}}`}</p>
              <div className="flex justify-end gap-2"><Button variant="ghost" size="xs" onClick={() => setIsAddingCustom(false)}>Cancel</Button><Button size="xs" onClick={saveCustomField} disabled={!customForm.label.trim() || !customForm.key.trim() || duplicateKey}>Add field</Button></div>
            </div>
          )}
          {customPlaceholders.map((field) => (
            <div key={field.id} className="group flex items-center gap-2 border-t border-border-secondary px-2 py-2"><div className="min-w-0 flex-1"><div className="text-xs font-medium text-text-primary">{field.label}</div><div className="font-mono text-[11px] text-accent-primary">{`{{custom.${field.key}}}`}</div></div><Button size="xs" aria-label={`Insert ${field.label}`} onClick={() => insert(`{{custom.${field.key}}}`, `custom.${field.key}`)}>Insert</Button><Button size="xs" variant="ghost" iconOnly aria-label={`Delete ${field.label}`} onClick={() => onCustomPlaceholdersChange(customPlaceholders.filter((candidate) => candidate.id !== field.id))}><Trash2 className="h-3.5 w-3.5" /></Button></div>
          ))}
        </section>

        <section className="mb-2 rounded-md border border-border-primary">
          <h3 className="px-2 py-2 text-xs font-semibold text-text-primary">Partials</h3>
          <div className="border-t border-border-secondary">{isLoadingPartials ? <p className="p-3 text-xs text-text-muted">Loading partials…</p> : partials.length === 0 ? <p className="p-3 text-xs text-text-muted">No partials available.</p> : partials.map((partial) => <div key={partial.id} className="flex items-center gap-2 px-2 py-2"><div className="min-w-0 flex-1"><div className="text-xs font-medium text-text-primary">{partial.displayName || partial.name}</div><div className="font-mono text-[11px] text-accent-primary">{`{{>${partial.name}}}`}</div></div><Button size="xs" aria-label={`Insert ${partial.displayName || partial.name}`} onClick={() => insert(`{{>${partial.name}}}`, `partial.${partial.name}`)}>Insert</Button></div>)}</div>
        </section>

        {!isPartialMode && mergedPlaceholders.some((field) => field.source === 'partial') && (
          <section className="rounded-md border border-border-primary"><h3 className="px-2 py-2 text-xs font-semibold text-text-primary">Partial placeholders</h3>{Object.entries(mergedPlaceholders.filter((field) => field.source === 'partial').reduce<Record<string, MergedPlaceholder[]>>((groups, field) => { const key = field.sourceName || 'unknown'; (groups[key] ||= []).push(field); return groups; }, {})).map(([sourceName, fields]) => <div key={sourceName} className="border-t border-border-secondary p-2"><p className="mb-2 text-[11px] font-medium text-text-secondary">From: {fields[0].sourceDisplayName || sourceName}</p>{fields.map((field) => <label key={field.id} className="mb-2 flex items-center gap-2 text-xs text-text-secondary"><span className="min-w-0 flex-1 truncate">{field.label}</span><select aria-label={`Link ${field.label}`} value={partialPlaceholderLinkings[field.key] || ''} onChange={(event) => onPartialPlaceholderLinkingChange?.(field.key, event.target.value || undefined)} className="h-7 max-w-36 rounded border border-border-primary bg-background-primary px-1 text-xs text-text-primary"><option value="">Always show</option>{templateBooleanPlaceholders.map((booleanField) => <option key={booleanField.id} value={booleanField.key}>Show when: {booleanField.label}</option>)}</select></label>)}</div>)}</section>
        )}
      </div>

      <GuidedLoopDialog collection={activeBuilder === 'loop-directors' ? 'directors' : activeBuilder === 'loop-shareholders' ? 'shareholders' : null} onClose={() => setActiveBuilder(null)} onInsert={(html, key) => { insert(html, key); setActiveBuilder(null); }} />
      <GuidedConditionDialog isOpen={activeBuilder === 'condition'} onClose={() => setActiveBuilder(null)} onInsert={(html) => { insert(html, 'condition'); setActiveBuilder(null); }} />
    </div>
  );
}

function GuidedLoopDialog({ collection, onClose, onInsert }: { collection: TemplateCollection | null; onClose: () => void; onInsert: (html: string, key: string) => void }) {
  const [fields, setFields] = useState<string[]>([]);
  const [layout, setLayout] = useState<TemplateLoopLayout>('paragraphs');
  if (!collection) return null;
  const option = TEMPLATE_COLLECTION_OPTIONS.find((candidate) => candidate.value === collection)!;
  const title = `Build ${option.label.toLowerCase()} loop`;
  const fieldLabel = collection === 'directors' ? 'Director' : 'Shareholder';
  const preview = fields.length ? buildEachBlock({ collection, fields, layout }) : '';
  return <Modal isOpen onClose={onClose} title={title} description="Choose the fields and starter layout to insert a complete loop." size="md"><ModalBody className="space-y-4"><fieldset><legend className="mb-2 text-xs font-semibold text-text-primary">Fields</legend><div className="space-y-2">{TEMPLATE_FIELD_OPTIONS[collection].map((field) => <label key={field.value} className="flex items-center gap-2 text-sm text-text-secondary"><input type="checkbox" aria-label={`${fieldLabel} ${field.label.toLowerCase()}`} checked={fields.includes(field.value)} onChange={(event) => setFields((previous) => event.target.checked ? [...previous, field.value] : previous.filter((value) => value !== field.value))} />{field.label}</label>)}</div></fieldset><label className="block text-xs font-medium text-text-secondary">Starter layout<select value={layout} onChange={(event) => setLayout(event.target.value as TemplateLoopLayout)} className="mt-1 h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary"><option value="paragraphs">Paragraphs</option><option value="bullets">Bullets</option><option value="table">Table</option></select></label><details className="rounded-md border border-border-primary p-2"><summary className="cursor-pointer text-xs font-medium text-text-secondary">View syntax</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap font-mono text-[11px] text-accent-primary">{preview || 'Select one or more fields to preview the generated syntax.'}</pre></details></ModalBody><ModalFooter><Button variant="secondary" size="sm" onClick={onClose}>Cancel</Button><Button size="sm" onClick={() => onInsert(buildEachBlock({ collection, fields, layout }), `loop.${collection}`)} disabled={fields.length === 0}>Insert loop</Button></ModalFooter></Modal>;
}

function GuidedConditionDialog({ isOpen, onClose, onInsert }: { isOpen: boolean; onClose: () => void; onInsert: (html: string) => void }) {
  const [field, setField] = useState(CONDITION_FIELDS[0]);
  const [operator, setOperator] = useState<ConditionOperator>('truthy');
  const [value, setValue] = useState('');
  const [body, setBody] = useState('Condition content');
  let preview = '';
  let conditionError = '';
  if (body) {
    try {
      preview = buildConditionBlock({ field, operator, value: operator === 'truthy' ? undefined : value, bodyHtml: `<p>${escapeText(body)}</p>` });
    } catch (error) {
      conditionError = error instanceof Error ? error.message : 'Enter a safe comparison value.';
    }
  }
  return <Modal isOpen={isOpen} onClose={onClose} title="Build condition" description="Generate a balanced conditional block." size="md"><ModalBody className="space-y-4"><label className="block text-xs font-medium text-text-secondary">Show content when<select value={field} onChange={(event) => setField(event.target.value)} className="mt-1 h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary">{CONDITION_FIELDS.map((candidate) => <option key={candidate} value={candidate}>{candidate}</option>)}</select></label><label className="block text-xs font-medium text-text-secondary">Comparison<select value={operator} onChange={(event) => setOperator(event.target.value as ConditionOperator)} className="mt-1 h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary"><option value="truthy">has a value</option><option value="equals">equals</option><option value="notEquals">does not equal</option></select></label>{operator !== 'truthy' && <label className="block text-xs font-medium text-text-secondary">Value<input value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary" /></label>}<label className="block text-xs font-medium text-text-secondary">Content<input value={body} onChange={(event) => setBody(event.target.value)} className="mt-1 h-8 w-full rounded-md border border-border-primary bg-background-primary px-2 text-xs text-text-primary" /></label>{conditionError && <p className="text-xs text-status-error">{conditionError}</p>}<details className="rounded-md border border-border-primary p-2"><summary className="cursor-pointer text-xs font-medium text-text-secondary">View syntax</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap font-mono text-[11px] text-accent-primary">{preview}</pre></details></ModalBody><ModalFooter><Button variant="secondary" size="sm" onClick={onClose}>Cancel</Button><Button size="sm" onClick={() => onInsert(buildConditionBlock({ field, operator, value: operator === 'truthy' ? undefined : value, bodyHtml: `<p>${escapeText(body)}</p>` }))} disabled={!body || Boolean(conditionError) || (operator !== 'truthy' && !value)}>Insert condition</Button></ModalFooter></Modal>;
}
