import type { A4PageEditorRef } from '@/components/documents/a4-page-editor';

/**
 * Inserts template syntax without escaping structural HTML generated by guided
 * builders. Plain placeholders are safe HTML fragments too, so one insertion
 * path keeps the editor and preview representations consistent.
 */
export function insertTemplateSnippet(
  editor: Pick<A4PageEditorRef, 'insertHtmlAtCursor'> | null,
  html: string,
): void {
  editor?.insertHtmlAtCursor(html);
}
