-- Canonical aliases are generated by the same pinned application normalizer as
-- canonicalName. The application rollout gate remains closed until backfill completes.
ALTER TABLE "contacts" ADD COLUMN "canonicalAlias" TEXT;

CREATE INDEX "contacts_tenantId_contactType_deletedAt_canonicalAlias_idx"
    ON "contacts"("tenantId", "contactType", "deletedAt", "canonicalAlias");
