import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Bundles the A4 pagination engine for use inside the export Chromium page.
 * Regenerate with `npm run generate:pagination-bundle` after editing any of
 * the pagination modules.
 */
const root = dirname(dirname(fileURLToPath(import.meta.url)));

async function main() {
  const result = await build({
    entryPoints: [
      join(root, 'src/components/documents/a4-pagination/paginate-in-browser.entry.ts'),
    ],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: 'es2017',
    globalName: 'A4Pagination',
  });

  const script = result.outputFiles[0].text;
  const output = join(
    root,
    'src/components/documents/a4-pagination/pagination-bundle.generated.ts',
  );
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(
    output,
    [
      '// Generated by scripts/build-pagination-bundle.mts — do not edit.',
      '// Regenerate with: npm run generate:pagination-bundle',
      `export const A4_PAGINATION_BUNDLE = ${JSON.stringify(script)};\n`,
    ].join('\n'),
  );
  console.info(`Wrote ${output} (${script.length} chars)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
