import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative, sep } from 'node:path';
import process from 'node:process';

const root = process.cwd();
const sourceRoot = join(root, 'src', 'services');
const outputPath = join(root, 'src', 'generated', 'business-assistant-capability-registry.ts');
const checkOnly = process.argv.includes('--check');

async function filesUnder(directory: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw error;
  }
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await filesUnder(full));
    else if (entry.isFile() && extname(entry.name) === '.ts' && entry.name === 'assistant-capabilities.ts') files.push(full);
  }
  return files;
}

function moduleSpecifier(file: string): string {
  const rel = relative(join(root, 'src'), file).split(sep).join('/').replace(/\.ts$/, '');
  if (!/^services(?:\/[a-zA-Z0-9_.-]+)+$/.test(rel)) throw new Error(`Unsafe capability manifest path: ${rel}`);
  return `@/${rel}`;
}

const files = (await filesUnder(sourceRoot)).sort((a, b) => moduleSpecifier(a).localeCompare(moduleSpecifier(b)));
const manifests: Array<{ file: string; specifier: string; alias: string }> = [];
for (const file of files) {
  const source = await readFile(file, 'utf8');
  if (!/\bexport\s+(?:const|function)\s+assistantCapabilities\b/.test(source)) {
    throw new Error(`${moduleSpecifier(file)} must export assistantCapabilities`);
  }
  manifests.push({ file, specifier: moduleSpecifier(file), alias: `capabilities${manifests.length}` });
}

const importLines = manifests.map(({ specifier, alias }) => `import { assistantCapabilities as ${alias} } from '${specifier}';`);
const values = manifests.length === 0 ? '[]' : `[\n${manifests.map(({ alias }) => `  ...${alias},`).join('\n')}\n]`;
const generated = `/**\n * Generated by scripts/generate-business-assistant-registry.mts.\n * Do not edit by hand.\n */\n${importLines.join('\n')}${importLines.length ? '\n' : ''}import { BusinessAssistantCapabilityRegistry } from '@/services/business-assistant/contracts';\n\nexport const businessAssistantCapabilities = ${values} as const;\nexport const businessAssistantCapabilityRegistry = new BusinessAssistantCapabilityRegistry(businessAssistantCapabilities);\nexport default businessAssistantCapabilities;\n`;

if (checkOnly) {
  let current = '';
  try { current = await readFile(outputPath, 'utf8'); } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  if (current !== generated) {
    process.stderr.write('Business Assistant capability registry is stale. Run generate:assistant-capabilities.\n');
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated, 'utf8');
}

// Keep an explicit dependency on dirname so bundlers do not treat this as a
// browser module when a build accidentally includes scripts.
void dirname(outputPath);
